=== raymondwanyoike/converge-ecms-1.x/converge-server/modules/converge-war/src/main/resources/dk/i2m/converge/menu.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="menuItem" type="menuItem"/>

    <xs:element name="menuItems" type="menuItems"/>

    <xs:complexType name="menuItem">
        <xs:sequence>
            <xs:element name="children" type="menuItem" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="label" type="xs:string" minOccurs="0"/>
            <xs:element name="action" type="xs:string" minOccurs="0"/>
            <xs:element name="role" type="xs:string" minOccurs="0"/>
            <xs:element name="privilege" type="xs:string" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="active" type="xs:boolean" use="required"/>
        <xs:attribute name="id" type="xs:string" use="required"/>
        <xs:attribute name="resetOnClick" type="xs:boolean" use="required"/>
        <xs:attribute name="resetSectionMenu" type="xs:boolean" use="required"/>
        <xs:attribute name="sectionMenu" type="xs:boolean" use="required"/>
        <xs:attribute name="type" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="menuItems">
        <xs:sequence>
            <xs:element name="item" type="menuItem" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== raymondwanyoike/converge-ecms-1.x/converge-server/modules/converge-war/src/main/resources/dk/i2m/converge/menu.xml
<?xml version="1.0" encoding="UTF-8"?>

<menuItems xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
  xsi:noNamespaceSchemaLocation="menu.xsd">

    <item id="lnkDashboard" active="true">
        <label>DASHBOARD</label>
        <action>/index</action>
    </item>

    <item id="lnkInbox">
        <label>INBOX</label>
        <action>/inbox</action>
        <privilege>MY_NEWS_ITEMS</privilege>
        <privilege>MY_PHOTOS</privilege>
    </item>

    <item id="lnkCalendar">
        <label>CALENDAR</label>
        <action>/calendar</action>
    </item>

    <item id="lnkPlanning">
        <label>PLANNING</label>
        <action>/planning/editions</action>
        <privilege>OUTLET_PLANNING</privilege>
    </item>

    <item id="lnkNewswires">
        <label>NEWSWIRES</label>
        <action>/newswires</action>
    </item>
    
    <item id="lnkAdvancedSearch">
        <label>menu_SEARCH</label>
        <action>/search</action>
    </item>

    <item id="lnkListings">
        <label>menu_LISTINGS</label>
        <action>/listings</action>
        <privilege>LISTINGS</privilege>
    </item>

    <item id="lnkConcepts">
        <label>CONCEPTS</label>
        <action>/concepts</action>
    </item>
    
    <item id="lnkContacts">
        <label>CONTACTS</label>
        <action>/contacts</action>
        <privilege>CONTACTS_MANAGE</privilege>
        <privilege>CONTACTS_READ</privilege>
    </item>
    

    <!--item id="lnkHelp" type="submenu">
        <label>menu_HELP</label>
        <action>/help</action>
    </item-->

    <item id="lnkMyProfile" type="submenu">
        <label>menu_MY_PROFILE</label>
        <action>/myprofile</action>
    </item>
    
    <item id="lnkReporting" type="submenu">
        <label>menu_REPORTING</label>
        <action>/reporting</action>
        <privilege>REPORTING</privilege>
    </item>

    
    <item id="lnkNewsreader" type="submenu">
        <label>menu_NEWS_READER</label>
        <action>/newsreader</action>
        <privilege>NEWS_READER</privilege>
    </item>

    <item id="lnkAdministration" type="admin">
        <label>ADMINISTRATION</label>
        <action>/administration/administration</action>
        <role>ADMINISTRATOR</role>

        <children id="lnkAdministrationConfiguration" resetOnClick="false">
            <action>/administration/configuration</action>
            <label>CONFIGURATION</label>
            <role>ADMINISTRATOR</role>
        </children>
        
        <children id="lnkAdministrationUsers" resetOnClick="false" sectionMenu="true">
            <action>/administration/user_sessions</action>
            <label>USERS</label>
            <role>ADMINISTRATOR</role>

            <children id="lnkAdministrationUserSessions" resetOnClick="false" sectionMenu="false" resetSectionMenu="false">
                <action>/administration/user_sessions</action>
                <label>ADMIN_MENU_USER_SESSIONS</label>
                <role>ADMINISTRATOR</role>
            </children>

            <children id="lnkAdministrationUserList" resetOnClick="false" sectionMenu="false" resetSectionMenu="false">
                <action>/administration/users</action>
                <label>ADMIN_MENU_USERS</label>
                <role>ADMINISTRATOR</role>
            </children>

            <children id="lnkAdministrationUserrole" resetOnClick="false" sectionMenu="false" resetSectionMenu="false">
                <action>/administration/user_roles</action>
                <label>ADMIN_MENU_USER_ROLES</label>
                <role>ADMINISTRATOR</role>
            </children>
        </children>

        <children id="lnkAdministrationOutlets" resetOnClick="false" sectionMenu="true">
            <action>/administration/outlets</action>
            <label>OUTLETS</label>
            <role>ADMINISTRATOR</role>

            <children id="lnkOutlets" resetOnClick="false" sectionMenu="false" resetSectionMenu="false">
                <action>/administration/outlets</action>
                <label>OUTLETS</label>
                <role>ADMINISTRATOR</role>
            </children>
        </children>

        <children id="lnkAdministrationWorkflows" sectionMenu="false" resetOnClick="false">
            <action>/administration/workflows</action>
            <label>WORKFLOWS</label>
            <role>ADMINISTRATOR</role>
        </children>

        <children id="lnkAdministrationNewswires" sectionMenu="false" resetOnClick="false">
            <action>/administration/newswires</action>
            <label>NEWSWIRES</label>
            <role>ADMINISTRATOR</role>
        </children>

        <children id="lnkAdministrationCatalogues" resetOnClick="false" sectionMenu="true">
            <action>/administration/catalogues</action>
            <label>CATALOGUES</label>
            <role>ADMINISTRATOR</role>

            <children id="lnkMediaRepositories" resetOnClick="false" sectionMenu="false" resetSectionMenu="false">
                <action>/administration/media_repositories</action>
                <label>MEDIA_REPOSITORIES</label>
                <role>ADMINISTRATOR</role>
            </children>

            <children id="lnkRenditions" resetOnClick="false" sectionMenu="false" resetSectionMenu="false">
                <action>/administration/renditions</action>
                <label>mediaitem_RENDITIONS</label>
                <role>ADMINISTRATOR</role>
            </children>
        </children>

        <children id="lnkAdministrationCalendar" resetOnClick="false" sectionMenu="true">
            <action>/administration/calendar_categories</action>
            <label>calendar_CALENDAR</label>
            <role>ADMINISTRATOR</role>

            <children id="lnkAdministrationCalendarCategories" resetOnClick="false" sectionMenu="false" resetSectionMenu="false">
                <action>/administration/calendar_categories</action>
                <label>calendar_CATEGORIES</label>
                <role>ADMINISTRATOR</role>
            </children>

        </children>

        <children id="lnkAdministrationTimers" resetOnClick="false">
            <action>/administration/timers</action>
            <label>administrator_timer_PAGE_TITLE</label>
            <role>ADMINISTRATOR</role>
        </children>
        
        <children id="lnkAdministrationSearchEngine" resetOnClick="false">
            <action>/administration/search_engine</action>
            <label>administrator_search_engine_PAGE_TITLE</label>
            <role>ADMINISTRATOR</role>
        </children>


        <children id="lnkAdministrationPlugins" resetOnClick="false">
            <action>/administration/plugins</action>
            <label>administrator_plugins_PAGE_TITLE</label>
            <role>ADMINISTRATOR</role>
        </children>

        <children id="lnkAdministrationAnnouncements" resetOnClick="false">
            <action>/administration/announcements</action>
            <label>announcements_ANNOUNCEMENTS</label>
            <role>ADMINISTRATOR</role>
        </children>

        <children id="lnkAdministrationLanguages" resetOnClick="false">
            <action>/administration/languages</action>
            <label>language_LANGUAGES</label>
            <role>ADMINISTRATOR</role>
        </children>


    </item>
</menuItems>
